version: '2'
services:
    cscart:
        container_name: my-cscart
        build: ./dockerfiles/centos7-cscart-php56
        # image: reneice/docker-centos-cscart
        environment:
            SERVER_NAME: www.example.com:80
            STDOUT_ERROR_LOG: "TRUE"
            STDOUT_CUSTOM_LOG: "FALSE"
        ports:
            - 8101:80
        volumes:
            - ./docroot:/var/www/html
        links:
            - db:db
        tty: true
    db:
        container_name: my-cscart-mariadb
        image: mariadb
        ports:
            - 3306:3306
        volumes:

            # I used to because of mysqldump or exec sql files.
            # If do not use please delete.
            - ./mariadb/other_data:/other_data

            # If Mac of Windows is Permission Error occurs.
            # Sorry. I still do not know the solution.
            # - ./mariadb/database:/var/lib/mysql

        environment:
            MYSQL_ROOT_PASSWORD: cscart
            MYSQL_PASSWORD: cscart
            MYSQL_USER: cscart
            MYSQL_DB: cscart
