version: '2'
services:
    cscart:
        container_name: cscart
        build: ./dockerfiles/centos7-cscart-php56
        # image: reneice/docker-centos-cscart
        environment:
            SERVER_NAME: www.example.com:80
            STDOUT_ERROR_LOG: "FALSE"
            STDOUT_CUSTOM_LOG: "FALSE"
        ports:
            - 8101:80
        volumes:
            - ./docroot:/var/www/html
        links:
            - db:db
        tty: true
    db:
        container_name: cscart_mariadb
        image: mariadb
        ports:
            - 3306:3306
        volumes:
            - ./mariadb/other_data:/other_data
            - ./mariadb/database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: cscart
            MYSQL_PASSWORD: cscart
            MYSQL_USER: cscart
            MYSQL_DB: cscart
